import { getArticles } from "@/lib/articles";
import { OG_CONTENT_TYPE, OG_SIZE, renderOgCard } from "@/lib/og";

/**
 * Social card for the /training index. Per-article cards are generated by
 * app/training/[slug]/opengraph-image.tsx; both share the layout in src/lib/og.tsx.
 */

export const alt = "Bedrock.fit Training: evidence-based strength and endurance articles";
export const size = OG_SIZE;
export const contentType = OG_CONTENT_TYPE;

export default async function Image() {
  const articles = getArticles();
  const sourceCount = articles.reduce((n, a) => n + a.sources.length, 0);

  return renderOgCard({
    eyebrow: "Editorial",
    title: "Training, with the receipts",
    accent: "with the receipts",
    dek: "Long-form articles on getting and staying strong. No citation, no claim.",
    stats: [
      [`${articles.length}`, articles.length === 1 ? "article" : "articles"],
      [`${sourceCount}`, "cited sources"],
      ["4", "categories"],
    ],
  });
}
